<a href="https://colab.research.google.com/github/DavidCruz1013/etl-data-pipeline/blob/main/Polizas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
https://raw.githubusercontent.com/DavidCruz1013/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv

**Importar libreria**

In [1]:
import pandas as pd

**Cargar el CSV de polizas**

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DavidCruz1013/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv")

df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

**Explorar los datos**

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

**Crear copia para limpiar datos**

In [4]:
polizas = df.copy()

polizas.columns = polizas.columns.str.strip().str.lower()

for col in polizas.select_dtypes(include='object').columns:
    polizas[col] = polizas[col].astype(str).str.strip()

polizas = polizas.replace(r'^\s*$', pd.NA, regex=True)

**Limpiar columnas importantes**

In [8]:
#Convertir fechas
polizas['fecha_emision'] = pd.to_datetime(
    polizas['fecha_emision'],
    errors='coerce'
)

**Limpiar numero porque vienen con comas**

In [7]:
polizas['prima'] = polizas['prima'].astype(str).str.replace(',', '.', regex=False)
polizas['comision'] = polizas['comision'].astype(str).str.replace(',', '.', regex=False)
polizas['monto_asegurado'] = polizas['monto_asegurado'].astype(str).str.replace(',', '', regex=False)

polizas['prima'] = pd.to_numeric(polizas['prima'], errors='coerce')
polizas['comision'] = pd.to_numeric(polizas['comision'], errors='coerce')
polizas['monto_asegurado'] = pd.to_numeric(polizas['monto_asegurado'], errors='coerce')

**Eliminar duplicados**

In [9]:
polizas = polizas.drop_duplicates()

Separar registros validos y rechazados

In [10]:
validos = polizas[
    polizas['fecha_emision'].notna() &
    polizas['prima'].notna() &
    polizas['monto_asegurado'].notna()
].copy()

rechazados = polizas[
    polizas['fecha_emision'].isna() |
    polizas['prima'].isna() |
    polizas['monto_asegurado'].isna()
].copy()

**Motivo de rechazo**

In [11]:
def motivo(row):

    motivos = []

    if pd.isna(row['fecha_emision']):
        motivos.append("fecha_invalida")

    if pd.isna(row['prima']):
        motivos.append("prima_invalida")

    if pd.isna(row['monto_asegurado']):
        motivos.append("monto_invalido")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

**Exportar CSV**

In [12]:
validos.to_csv("polizas_curated.csv", index=False)

rechazados.to_csv("polizas_rejects.csv", index=False)

**Conectar a PostgreSQL**

In [13]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

database_url = "postgresql://etl_cruz:QQKUpHpEiAA9Xpnfx2CpRPN4SRonP1Mc@dpg-d6qu6mc50q8c73bpejbg-a.oregon-postgres.render.com/etl_seguros_ej65"

engine = create_engine(database_url)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 41.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

**Insertar en la base de datos**

In [14]:
validos.to_sql(
    'polizas_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'polizas_rejects',
    engine,
    if_exists='append',
    index=False
)

960

**Verificar datos**

In [15]:
pd.read_sql(
"SELECT * FROM polizas_curated LIMIT 10",
engine
)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,10,2026-01-24,2281,69,13,3,791.38,67.44,20710.00000
1,26,2025-07-29,2295,71,11,4,614.46,149.78,36670.97000
2,45,2025-12-11,2278,66,3,11,1539.37,240.41,114732.26000
3,49,2025-08-11,1122,2,14,4,337.32,69.59,47210.14000
4,50,2025-02-22,717,49,15,10,518.78,86.45,66.87199
5,66,2025-03-04,1352,21,12,6,776.33,147.21,112829.12000
6,82,2025-07-18,2392,21,3,4,0.00,83.63,33866.99000
7,99,2025-05-12,490,57,1,1,716.12,159.79,23929.67000
8,104,2025-10-20,3524,7,11,8,149.44,10.64,17925.05000
9,159,2025-09-04,1637,5,2,5,748.78,82.65,84100.56000