<a href="https://colab.research.google.com/github/DavidCruz1013/etl-data-pipeline/blob/main/Siniestros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
https://raw.githubusercontent.com/DavidCruz1013/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv

**Importar la Libreria**

In [1]:
import pandas as pd

**Cargar el CSV**

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DavidCruz1013/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv")

df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

**Importar los datos**

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

**Creamos una copia para la limpieza**

In [4]:
siniestros = df.copy()

siniestros.columns = siniestros.columns.str.strip().str.lower()

for col in siniestros.select_dtypes(include='object').columns:
    siniestros[col] = siniestros[col].astype(str).str.strip()

siniestros = siniestros.replace(r'^\s*$', pd.NA, regex=True)

**Convertimos las Fechas**

In [5]:
siniestros['fecha_siniestro'] = pd.to_datetime(
    siniestros['fecha_siniestro'],
    errors='coerce'
)

/tmp/ipykernel_174/1711211165.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  siniestros['fecha_siniestro'] = pd.to_datetime(

**Limpiar columnas numericas **

In [6]:
siniestros['monto_siniestro'] = siniestros['monto_siniestro'].astype(str).str.replace(',', '.', regex=False)

siniestros['monto_siniestro'] = pd.to_numeric(
    siniestros['monto_siniestro'],
    errors='coerce'
)

**Limpiamos duplicados**

In [7]:
siniestros = siniestros.drop_duplicates()

**Separar datos validos y rechazados**

In [8]:
validos = siniestros[
    siniestros['fecha_siniestro'].notna() &
    siniestros['monto_siniestro'].notna()
].copy()

rechazados = siniestros[
    siniestros['fecha_siniestro'].isna() |
    siniestros['monto_siniestro'].isna()
].copy()

**Motivo de rechazo**

In [9]:
def motivo(row):

    motivos = []

    if pd.isna(row['fecha_siniestro']):
        motivos.append("fecha_invalida")

    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_invalido")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

**Conectar a PostgreSQL**

In [10]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

database_url = "postgresql://etl_cruz:QQKUpHpEiAA9Xpnfx2CpRPN4SRonP1Mc@dpg-d6qu6mc50q8c73bpejbg-a.oregon-postgres.render.com/etl_seguros_ej65"

engine = create_engine(database_url)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 61.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

**Insertar los datos en PostgreSQL**

In [11]:
validos.to_sql(
    'siniestros_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'siniestros_rejects',
    engine,
    if_exists='append',
    index=False
)

226

**Verificamos los datos cargados **

In [12]:
pd.read_sql(
"SELECT * FROM siniestros_curated LIMIT 10",
engine
)

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    ABIERTO
1             3      15785      2025-09-19           702.27    cerrado
2             8      23824      2025-01-17          2736.20    ABIERTO
3            13       3716      2025-07-13         -4274.39  Rechazado
4            24      17180      2025-06-13          6183.83    cerrado
5            27      22625      2025-03-07           141.77        nan
6            33       2231      2025-09-21          2443.90  Rechazado
7            36      16929      2025-01-06          3649.94    cerrado
8            45      15100      2025-01-27          8761.24    ABIERTO
9            66      14064      2025-03-25          9842.05    Abierto